// Map from extended language keywords to their TypeScript equivalents.
export const keywordMap: Record<string, string> = {
  fucking: "class",
  fuckingFunction: "function",
  fuckingReturn: "return",
  fuckingExtends: "extends",
  fuckingImplements: "implements",
  fuckingPublic: "public",
  fuckingPrivate: "private",
  fuckingProtected: "protected",
  fuckingStatic: "static",
  fuckingAbstract: "abstract",
  fuckingNew: "new",
  fuckingInterface: "interface",
  fuckingType: "type",
  fuckingVar: "var",
  fuckingConst: "const",
  fuckingLet: "let",
  fuckingConstructor: "constructor",
  fuckingThis: "this",
  fuckingSuper: "super",
  fuckingIf: "if",
  fuckingElse: "else",
  fuckingSwitch: "switch",
  fuckingCase: "case",
  fuckingDefault: "default",
  fuckingFor: "for",
  fuckingWhile: "while",
  fuckingDo: "do",
  fuckingBreak: "break",
  fuckingContinue: "continue",
  fuckingTry: "try",
  fuckingCatch: "catch",
  fuckingFinally: "finally",
  fuckingThrow: "throw",
  fuckingImport: "import",
  fuckingExport: "export",
  fuckingFrom: "from",
  fuckingAs: "as",
  fuckingNamespace: "namespace",
  fuckingModule: "module",
  fuckingDeclare: "declare",
  fuckingReadonly: "readonly",
  fuckingGet: "get",
  fuckingSet: "set",
};

export type CustomKeyword = keyof typeof keywordMap;
